# Ce fichier est important pour React
# Il permet à React Router de gérer les routes côté front : si Nginx ne trouve pas le lien (par exemple /dashboard)
# Au lieu de renvoyer une erreur 404, il redirige vers index.html, et c’est React Router qui affiche la bonne page.

server {
    listen 80;

    # Dossier racine où se trouvent les fichiers compilés
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Essaie de trouver le fichier demandé
        # Si pas trouvé → renvoie index.html (React Router prend le relais)
        try_files $uri $uri/ /index.html;
    }

    # Optimisation : mise en cache des assets (JS, CSS, images)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}