# Configuration Nginx pour une application Laravel :
# redirige toutes les requêtes vers index.php et transmet les fichiers PHP à PHP-FPM pour exécution.

server {
    listen 8000;

    root /var/www/html/public;
    index index.php;

    # Toutes les requêtes passent par index.php (Laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM traite les fichiers .php
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}